name: mv_player
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.1.0
  flutter_onboarding_slider: ^1.0.11
  curved_navigation_bar: ^1.0.3
  lottie: ^2.6.0
  carousel_slider: ^4.2.1
  anim_search_bar: ^2.0.3
  shimmer: ^3.0.0
  permission_handler: ^11.0.1
  just_audio: ^0.9.35
  on_audio_query: ^2.9.0

  

  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/sample logo.jpg"

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter



flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
  

