name: mv_player
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.1.0
  flutter_onboarding_slider: ^1.0.11
  curved_navigation_bar: ^1.0.3
  lottie: ^2.7.0
  carousel_slider: ^4.2.1
  anim_search_bar: ^2.0.3
  shimmer: ^3.0.0
  permission_handler: ^9.2.0
  shared_preferences: ^2.2.2
  # ------------------ musics section ------------------
  just_audio: ^0.9.35
  on_audio_query: ^2.9.0
  audio_video_progress_bar: ^2.0.0
  just_audio_background: ^0.0.1-beta.10
  share_plus: ^7.2.1

  # ------------------ video section ------------------
  fetch_all_videos: ^1.0.5
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  video_player: ^2.8.1
  photo_manager: ^2.8.1

  


  


  

  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/sample logo.jpg"

dev_dependencies: 
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  hive_generator: ^2.0.1



flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
  

